### ISSUE TITLE
Badge Payment Issue

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#93]
xception 'Error' with message 'Call to undefined method backend\models\Badges::GetCart()' 

in /var/www/agc/backend/controllers/PaymentController.php:66

Stack trace:
#0 [internal function]: backend\controllers\PaymentController->actionCharge()
#1 /var/www/agc/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /var/www/agc/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#3 /var/www/agc/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction()
#4 /var/www/agc/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#5 /var/www/agc/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#6 /var/www/agc/backend/web/index.php(17): yii\base\Application->run()
#7 {main}

**Comment by sharkbit** [comment]
fixed
